# Generated by Django 6.0.2 on 2026-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_name_profile_first_name_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nonce_chain_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='nonce_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='nonce_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nonce_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nonce_uri',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nonce',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['wallet_address'], name='accounts_pr_wallet__c59f56_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['email'], name='accounts_pr_email_08cbb0_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['phone_number'], name='accounts_pr_phone_n_c27a97_idx'),
        ),
    ]
